Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in update_board: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in GUI initialization: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

Error in main: cannot identify image file 'board.svg'
Traceback (most recent call last):
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 145, in main
    gui = ChessGUI(root, fen)
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 48, in __init__
    self.update_board()
  File "/Users/edwardbaker/Documents/Code/chess/cpp/gui.py", line 69, in update_board
    image = Image.open("board.svg")
  File "/Users/edwardbaker/Documents/Code/chess/lib/python3.10/site-packages/PIL/Image.py", line 3532, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'board.svg'

